---
baseURL: https://paulayickvintagebrass.com/
languageCode: en-us
title: Paul Ayick
theme: hugo-fresh
googleAnalytics: 
uglyurls: false
permalinks:
  instruments: instruments/:slug/
taxonomies:
  instrument: instruments
markup:
  goldmark:
    renderer:
      unsafe: true
params:
  openGraph: true
  description: 
  navbarlogo:
    image: logos/name.svg
    link: "/"
  font:
    name: 
    sizes:
    - 400
    - 600
  hero:
    title: Vintage Brass.
    subtitle: Trumpets, Cornets, Brass, and Other Winds
    buttontext: Learn More
    buttonlink: learn-more
    image: logos/sabotage.jpeg
  navbar:
  - title: My Music
    url: "/music"
  - title: Trumpets
    url: "/pages/trumpets"
  - title: Cornets
    url: "/pages/cornets"
  - title: Mouthpieces
    url: "/pages/mouthpieces"
  - title: Misc
    url: "/pages/misc"
  - title: Custom
    url: "/pages/custom"
  - title: Sold
    url: "/pages/sold"
  - title: Contact
    url: "/contact"
    button: true
  sidebar:
    enable: true
    logo: symbol
    sections:
    - title: Trumpets
      icon: user
      path: trumpets
    - title: Cornets
      icon: envelope
      path: cornets
    - title: Mouthpieces
      icon: image
      path: mouthpieces
    - title: Misc
      icon: cog
      path: misc
  about:
    title: About Me
    subtitle: 'I''m a lifelong professional trumpet musician and teacher. I''ve played
      and taught all over the world, and have even had the privilege of performing
      with some of the biggest names in show business. I currently make my living
      by buying and selling vintage brass instruments, and I also work as a session
      musician in studios around town. I love making music and feel incredibly lucky
      to get to work with such fine instruments. '
    image: me-at-trpt-summit.jpg
    buttonText: My Music
    buttonLink: "/music"
  cards:
    title: ABOUT THIS WEBSITE AND A LITTLE ABOUT ME
    subtitle: ''
    tabs:
    - name: BACKGROUND
      quote: I'm a lifelong trumpet professional and I teach jazz and general music
        courses at Broward College in South Florida.I became interested in vintage
        trumpets when some 30 years ago I began seeking out an Olds Mendez trumpet
        like the one my father bought me in 1959 when I was 12. The search piqued
        my curiosity and a series of events eventually found me inheriting tools,
        and knowledge from some great local repaimen. As a player my first gigs were
        when I was 11 or 12 years old and I have had a long, exciting career in music.I
        have traveled extensively, played with name bands from the swing era, played
        shows, as well as with many small jazz bands with some of the greatest jazz
        musicians of our time.
      img: "1"
    - name: Quality
      quote: ' I have a fondness for trumpets from the first half of the 20th century
        and a look through my SOLD section will illustrate just what I have acquired
        and sold in the past. If any of the things you see in the main areas interest
        you contact me via e-mail I am interested in hearing from you about buying
        and sometimes trades. If you have Uncle Harry''s old trumpet and not sure
        what to do with it let me know I will tell you about it and make a fair offer
        if it is something I really like.The old trumpets may not be as consistent
        as what''s being built today but i find the best of them have a certain character
        to the sound. My old friend and bandmate Ira Sullivan RIP said "the have the
        voo".'
      img: "2"
    - name: Inquiries
      quote: Take a look around and browse through my collection of vintage brass
        instruments! When you find one you like, reach out and we'll make it happen.
        Finally visit my MUSIC page to hear some of my writing and playing.
      img: "3"
  section5: true
  footer:
    logo: Vintage.png
    socialmediatitle: Follow Me
    socialmedia:
    - link: https://www.linkedin.com/in/paul-ayick-7a98599/
      icon: linkedin
    - link: https://facebook.com/Paul-Ayick-Music-181953292011841/
      icon: facebook
    bulmalogo: false
    quicklinks:
      column3:
        title: Quick Links
        links:
        - text: My Music
          link: "/music"
        - text: My Favorite Sites
          link: "/links"
        - text: Contact
          link: "/contact"
        - text: Learn More
          link: "/learn-more"
