---
baseURL: https://paulayickvintagebrass.com/
languageCode: en-us
title: Paul Ayick
theme: hugo-fresh
googleAnalytics: 
uglyurls: false
permalinks:
  instruments: instruments/:slug/
taxonomies:
  series: series
  tag: tags
  name: names
  instrument: instruments
markup:
  goldmark:
    renderer:
      unsafe: true
params:
  openGraph: true
  description: 
  navbarlogo:
    image: logos/name.svg
    link: "/"
  font:
    name: Lexand Peta
    sizes:
    - 400
    - 600
  hero:
    title: Vintage Brass.
    subtitle: Trumpets, Cornets, Brass, and Other Winds
    buttontext: Learn More
    buttonlink: "#"
    image: logos/sabotage.jpeg
  navbar:
  - title: Trumpets
    url: "/pages/trumpets"
  - title: Cornets
    url: "/pages/cornets"
  - title: Mouthpieces
    url: "/pages/mouthpieces"
  - title: Misc
    url: "/pages/misc"
  - title: Custom
    url: "/pages/custom"
  - title: Sold
    url: "/pages/sold"
  - title: Contact
    url: "/contact"
    button: true
  sidebar:
    enable: true
    logo: symbol
    sections:
    - title: Trumpets
      icon: user
      path: trumpets
    - title: Cornets
      icon: envelope
      path: cornets
    - title: Mouthpieces
      icon: image
      path: mouthpieces
    - title: Misc
      icon: cog
      path: misc
  section1:
    enable: false
    title: Great power comes
    subtitle: with great responsibility
    tiles:
    - title: App builder
      icon: mouse-globe
      text: This is some explanatory text that is on two rows
      url: "/"
      buttonText: Free trial
    - title: Cloud integration
      icon: laptop-cloud
      text: This is some explanatory text that is on two rows
      url: "/"
      buttonText: Get started
    - title: Add-ons & plugins
      icon: plug-cloud
      text: This is some explanatory text that is on two rows
      url: "/"
      buttonText: Get started
  section2:
    enable: false
    title: You're here because you want the best
    subtitle: And we know it
    features:
    - title: Premium Quality
      text: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin ornare
        magna eros, eu pellentesque tortor vestibulum ut. Maecenas non massa sem.
        Etiam finibus odio quis feugiat facilisis.
      icon: laptop-globe
    - title: Premier Service
      text: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin ornare
        magna eros, eu pellentesque tortor vestibulum ut. Maecenas non massa sem.
        Etiam finibus odio quis feugiat facilisis.
      icon: doc-sync
    - title: 'Authenticity Guaranteed '
      text: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin ornare
        magna eros, eu pellentesque tortor vestibulum ut. Maecenas non massa sem.
        Etiam finibus odio quis feugiat facilisis.
      icon: mobile-feed
  section3:
    title: One Place
    subtitle: for Quality Vintage Wind Instruments
    image: me-at-trpt-summit.jpg
    buttonText: Reach Out
    buttonLink: "/contact"
  section4:
    title: Are you in the market for a quality vintage brass instrument?
    subtitle: ''
    clients:
    - name: Experienced
      quote: I'm a lifelong trumpet professional and teacher who has been in the business
        for over 20 years. I know what makes a quality brasswind instrument, and I
        am here to help you find one that's perfect for you.
      img: "1"
    - name: Quality
      quote: " I have a wide selection of vintage trumpets, cornets and horns that
        are perfect for any musician looking to add some history to their sound. You
        won't find instruments like these anywhere else."
      img: "2"
    - name: 'Professional '
      quote: Take a look around and browse through my collection of vintage brass
        instruments! When you find one you like, reach out and we'll make it happen.
      img: "3"
  section5: true
  footer:
    logo: Vintage.png
    socialmediatitle: Follow Me
    socialmedia:
    - link: https://www.linkedin.com/in/paul-ayick-7a98599/
      icon: linkedin
    - link: https://facebook.com/Paul-Ayick-Music-181953292011841/
      icon: facebook
    bulmalogo: false
    quicklinks:
      column3:
        title: Quick Links
        links:
        - text: My Music
          link: "/music"
        - text: My Favorite Sites
          link: "/links"
        - text: Contact
          link: "/contact"
