---
baseURL: https://paulayick.netlify.app/
languageCode: en-us
title: Paul Ayick
theme: hugo-fresh
googleAnalytics:
uglyurls: false
permalinks:
  instruments: instruments/:slug/
taxonomies:
  series: series
  tag: tags
  name: names
  instrument: instruments
markup:
  goldmark:
    renderer:
      unsafe: true
params:
  openGraph: true
  description:
  navbarlogo:
    image: logos/name.svg
    link: "/"
  font:
    name: Lexand Peta
    sizes:
    - 400
    - 600
  hero:
    title: Vintage Brass.
    subtitle: Trumpets, Cornets, Brass, and Other Winds
    buttontext: Learn More
    buttonlink: "#"
    image: logos/hero.svg
    clientlogos:
    - chicago_orchesta.png
    - boston_pops.png
  navbar:
  - title: Trumpets
    url: "/instruments/trumpets"
  - title: Cornets
    url: "/instruments/cornets"
  - title: Mouthpieces
    url: "/instruments/mouthpieces"
  - title: Misc
    url: "/instruments/miscellaneous"
  - title: Custom
    url: "/instruments/custom"
  - title: Sold
    url: "/instruments/sold"
  - title: Contact
    url: "/contact"
    button: true
  sidebar:
    enable: true
    logo: symbol
    sections:
    - title: Trumpets
      icon: user
      path: trumpets
    - title: Cornets
      icon: envelope
      path: cornets
    - title: Mouthpieces
      icon: image
      path: mouthpieces
    - title: Misc
      icon: cog
      path: misc
  section1:
    enable: false
    title: Great power comes
    subtitle: with great responsibility
    tiles:
    - title: App builder
      icon: mouse-globe
      text: This is some explanatory text that is on two rows
      url: "/"
      buttonText: Free trial
    - title: Cloud integration
      icon: laptop-cloud
      text: This is some explanatory text that is on two rows
      url: "/"
      buttonText: Get started
    - title: Add-ons & plugins
      icon: plug-cloud
      text: This is some explanatory text that is on two rows
      url: "/"
      buttonText: Get started
  section2:
    enable: false
    title: You're here because you want the best
    subtitle: And we know it
    features:
    - title: Premium Quality
      text: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin ornare
        magna eros, eu pellentesque tortor vestibulum ut. Maecenas non massa sem.
        Etiam finibus odio quis feugiat facilisis.
      icon: laptop-globe
    - title: Premier Service
      text: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin ornare
        magna eros, eu pellentesque tortor vestibulum ut. Maecenas non massa sem.
        Etiam finibus odio quis feugiat facilisis.
      icon: doc-sync
    - title: 'Authenticity Guaranteed '
      text: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin ornare
        magna eros, eu pellentesque tortor vestibulum ut. Maecenas non massa sem.
        Etiam finibus odio quis feugiat facilisis.
      icon: mobile-feed
  section3:
    title: One Place
    subtitle: for Quality Vintage Wind Instruments
    image: me-at-trpt-summit.jpg
    buttonText: Get started
    buttonLink: "#"
  section4:
    title: My Services
    subtitle: I buy and sell vintage brass, consult, appraise, and play trumpet professionally
    clients:
    - name: Vintage Brass
      quote: I strive for accuracy in the descriptions of each horn I sell, and all horns are shipped securely packaged, fully insured and sent promptly.
      img: "1"
    - name: Consultation
      quote: If you are someone who just discovered "Uncle Harry's" old horn in the attic, well then, you are just the kind of person I would like to hear from!
      img: "2"
    - name: Appraise
      quote: I work entirely from my home in South Florida where I also work as a trumpet player. I enjoy hearing from anyone with a question, comment, or just to say hello,  I always have time to "talk trumpet"
      img: "3"
  section5: true
  footer:
    logo: Vintage.png
    socialmediatitle: Follow Me
    socialmedia:
    - link: https://www.linkedin.com/in/paul-ayick-7a98599/
      icon: linkedin
    - link: https://facebook.com/Paul-Ayick-Music-181953292011841/
      icon: facebook
    bulmalogo: false
    quicklinks:
      column1:
        title: Product
        links:
        - text: Learn More
          link: ''
        - text: Why choose our product?
          link: "/"
      column2:
        title: Contact
        links:
        - text: Marketing
          link: ''
        - text: Lessons
          link: "/"
        - text: Purchase
          link: "/"
      column3:
        title: Terms
        links:
        - text: Terms and Conditions
          link: "/blog/first"
        - text: Privacy Policy
          link: "/blog/second"
